### ISSUE TITLE
light

### ISSUE THREAD

**Issue by tumuidle** [MCRcortex/vulkanite#10]
![image](https://github.com/MCRcortex/vulkanite/assets/62649962/1be9c9f5-48a9-42fc-812d-bb2f6fa6e079)
![image](https://github.com/MCRcortex/vulkanite/assets/62649962/87784685-6220-4340-9d19-d2325489665f)
![image](https://github.com/MCRcortex/vulkanite/assets/62649962/a687a87e-005c-4ce0-99e1-0722a1d23a7c)

**Comment by JorisDeBeer** [comment]
Do you have reprojection turned on in shader settings?
