### ISSUE TITLE
[BUG]: Not supported Intel Arc

### ISSUE THREAD

**Issue by HexYoF** [MCRcortex/vulkanite#14]
You _must_ include the following details:
- A longer description of the issue (where it occurs, when, can you reproduce it every time, etc.).

**No problems with iris on its own, if Vulkanite is added, iris reports errors.
The game works fine, just can't load Shaders**

- PC specs:
**CPU 12600k 
GPU Intel ARC A770**

**Comment by Bipbip2109** [comment]
Can't load any shader other than the demo one too, iris reports errors when trying to load mosts and crashes when trying to load lightweight ones probably lacking any kind of rt even non hardware.
Using a 2060 so not an Arc issue I'd guess

**Comment by HexYoF** [comment]
> Can't load any shader other than the demo one too, iris reports errors when trying to load mosts and crashes when trying to load lightweight ones probably lacking any kind of rt even non hardware. Using a 2060 so not an Arc issue I'd guess

No, I'm referring to the fact that shaders can be loaded correctly with just iris, but add Vulkanite MOD, and iris will report an error.

**Comment by Bipbip2109** [comment]
> > Can't load any shader other than the demo one too, iris reports errors when trying to load mosts and crashes when trying to load lightweight ones probably lacking any kind of rt even non hardware. Using a 2060 so not an Arc issue I'd guess
> 
> No, I'm referring to the fact that shaders can be loaded correctly with just iris, but add Vulkanite MOD, and iris will report an error.

Yeah that's what I'm saying

**Comment by miaotouy** [comment]
![OBS-NV12_2023-09-22 22-09-36 mkv_snapshot_00 45 974](https://github.com/MCRcortex/vulkanite/assets/66715028/fe2ff684-859d-4671-bc67-a8dbdadf72bd)

**Comment by bobcao3** [comment]
Iris shaders will not work on this mod right now. Not a bug of Intel GPUs
