### ISSUE TITLE
[BUG]: Strange noise shows in screen

### ISSUE THREAD

**Issue by Ptilopsis01** [MCRcortex/vulkanite#15]
![2023-09-20_15 21 03](https://github.com/MCRcortex/vulkanite/assets/93318731/715615b7-f803-4b98-9771-b2c486b34b34)
As you can see, there are lots of noise on screen, and the hand of player can not be rendered properly, which also happens to entities

**Comment by MCRcortex** [comment]
Entities are cause the mod is in pre-alpha, the noise is due to the shader pack
