### ISSUE TITLE
[BUG]: Sunlight goes through diffusive material in closed area

### ISSUE THREAD

**Issue by ECCQ700** [MCRcortex/vulkanite#20]
As shown below, sunlight always goes thorugh diffusive materials (glass, slime block, honey block, water, etc.) even when they have no direct access to sunlight
Same with moonlight
![2023-09-23_11 59 54](https://github.com/MCRcortex/vulkanite/assets/145807443/4961fb8e-720e-4035-850d-4e42ff647b38)
Environment:
Minecraft 1.20.1
Fabric 0.14.21
Fabric API 0.86.0
iris 1.6.8
Sodium 0.5.2
vulkanite 0.0.3

RTX 4060 laptop 8G
Driver version 537.42

**Comment by MCRcortex** [comment]
Shaderpack issue
