### ISSUE TITLE
[BUG]: Not functioning as expected

### ISSUE THREAD

**Issue by Stehsaer** [MCRcortex/vulkanite#22]
Visual glitch: unusable, no light source being emitted, some blocks are displaying as black, the sky is black, sometimes we get no ray tracing at all;
TEST CASE: /time set day
SCREENSHOT: 

No raytracing at all
![2023-09-24_10 45 22](https://github.com/MCRcortex/vulkanite/assets/54050160/ab0d09ff-595a-472b-87f9-f6b5eef95cf0)

Sometimes there is one, but look at the blocks at the ground
![2023-09-24_10 45 29](https://github.com/MCRcortex/vulkanite/assets/54050160/d7de0b9a-3f4c-417d-8ec1-7b85e0a0a28f)

![2023-09-24_10 49 37](https://github.com/MCRcortex/vulkanite/assets/54050160/86176ff4-c72d-42f0-a494-34095e0153ae)

![2023-09-24_10 47 39](https://github.com/MCRcortex/vulkanite/assets/54050160/17bca7f5-1a84-4a69-8fab-82e3ee046c8b)

Screen recording:

https://github.com/MCRcortex/vulkanite/assets/54050160/0c650b7e-87a8-473d-aaff-93121022e93c

Spec: i7-13620H, RTX 4060 Laptop GPU (8gigs of vram, vulkanite uses 2gigs), driver version Nvidia Studio Driver 537.42, system Windows 11 Professional 22H2 22621.2134
Minecraft 1.20.1, Sodium 0.5.8, Iris v1.6.8

Mod list:
appleskin mc1.20 2.5.0
durability mc1.20 1.10.5
dynamic  fps mc1.20 3.2.0
entityculling mc1.20.1 1.6.2
fabric api 0.89+1.20.1
fabric-language-kotlin
imblockerfabric 1.0.24
Jade mc1.20 11.6.0
journeymap mc1.20 5.9.8
libIPN mc1.20 3.0.2
modmenu 7.0.1
pinglist 1.4
vulkanite, sodium, iris

**Comment by MCRcortex** [comment]
Please make the issue on https://github.com/BalintCsala/VulkaniteDemoPack/issues

**Comment by Stehsaer** [comment]
> Please make the issue on https://github.com/BalintCsala/VulkaniteDemoPack/issues

Oh I thought it was an issue related to the mod XD. Sorry for reporting this in the wrong place
