### ISSUE TITLE
Whether vullkan is supported

### ISSUE THREAD

**Issue by safesaffawa** [MCRcortex/vulkanite#23]
Vullkan has a much bigger performance gain than soudim+iris.
So I think this mod could be a version of VulkanMod.
It would be great if this mod could be made into a version of VulkanMod to make up for the lack of lighting and shadows in VulkanMod.
It would be great if it could be implemented, and also optimised for this mod. After all, I'm not a professional developer, and I don't have the means to develop one on my own.

**Comment by sheikh1233** [comment]
this is not related to vulkanmod at all
all this mod does is use vulkan to enable your ray tracing cores in your gpu then uses them to run shaders in iris
