### ISSUE TITLE
Dependencies/ incompatibilities?

### ISSUE THREAD

**Issue by MihirGrand** [MCRcortex/vulkanite#38]
Can I run this mod alongside sodium? Do I use Iris to use the demo shader pack? What are some PBR capable resource packs you'd suggest that work well with vulkanite? The modrinth description was pretty short, and even though I know its still in alpha this project looks really cool and I couldn't wait so I decided to jump in and try it! 

Also, it doesn't need vulkan mod right?

**Comment by Bipbip2109** [comment]
Needs sodium and Iris to work.
For now only adds things for shaders to use RT if they were made for that.
No special PBR specifications needed.
Doesn't need Vulkan Mod (not compatible).

**Comment by MihirGrand** [comment]
Got it, thanks!
