### ISSUE TITLE
My idea in a nutshell (own VulkanMod). 

### ISSUE THREAD

**Issue by L2NE-dev** [MCRcortex/vulkanite#39]
I would like to make the best graphics mod in Minecraft ever, combining all the benefits of Sodium, Vulkan over OpenGL, OpenGL interop with Vulkan, VulkanMod, Blaze4D, Iris, Canvas, and maybe something else... and compatible with Immersive Portal Mod, with full ray tracing support and so on. 

But it's pity, that I'm in exile, and I've already lost the ability and confidence to do it. And initially I would like to completely rewrite the idea of VulkanMod, combined with the ideas of Blaze4D, to make a kind of Vulkan over OpenGL, with interop to the original OpenGL, if possible, with the possibility of ray tracing in the future. I would also like to take care of Immersive Portal Mod.

**Comment by andreasdc** [comment]
Sounds like too good to be true🤔but you have my full support

**Comment by unit-404** [comment]
I have ideas for creating a graphics engine for Minecraft, but first of all, it is especially and strictly exclusive only for Minecraft itself, and secondly the plan is still very and extremely costly, and I need just divine and gladiatorial forces to make even the minimum requirements and goals for it. And to do all this will have to do unfortunately alone... It's also idea of our VulkanMod, but to a bicubic degree.
