### ISSUE TITLE
Where is VULKANITE 0.0.4?

### ISSUE THREAD

**Issue by iekiekkeikei** [MCRcortex/vulkanite#46]
I can't find it on the Modrinth page, where can I find it?

**Comment by zERO123331** [comment]
as far as i know there is no "final" .jar for 0.0.4 and the last update to this repos main branch is from the same time 0.0.3 released on github.
i guess noone is really updating the main branch.
all of this could be wrong.
im just waiting for an update too

**Comment by iekiekkeikei** [comment]
Finally figured it out.
Looks like the vulkanite 0.0.4 I was looking for was made by the developer of dirt rt.
It wasn't the original one, so there was no point in reporting it here.
Sorry for setting up the strange issue...
