### ISSUE TITLE
Vulkanite doesn't run on my GTX 280

### ISSUE THREAD

**Issue by usermaf** [MCRcortex/vulkanite#47]
My GTX 280 dont work with the mod, please fix or i will die a slow and painful death from sugma.

**Comment by KarmaMarazu** [comment]
Maybe... maybe read and get a new card that isnt from 2008 it says rtx and up dont complain and have fun dying a slow and painful death from sugma

**Comment by usermaf** [comment]
EUEGUGUGHGUGUGUHGUGHUGHUGHGUGHUGHUGUGHGUHGUGHUGHUGHUGG

**Comment by Cuteistfox** [comment]
Get a card with rt first bro
