### ISSUE TITLE
Just black point.

### ISSUE THREAD

**Issue by Coloryr** [MCRcortex/vulkanite#9]
![image](https://github.com/MCRcortex/vulkanite/assets/26276037/9a115398-c11b-4091-9e75-ce291df89879)
![image](https://github.com/MCRcortex/vulkanite/assets/26276037/84c4b843-f92e-478a-846d-3d6100f2ed58)
![image](https://github.com/MCRcortex/vulkanite/assets/26276037/02d5936e-8fb5-4e37-8ed8-84173b10751f)

**Comment by tumuidle** [comment]
same with hight GPU 3D usage
![image](https://github.com/MCRcortex/vulkanite/assets/62649962/e5fdaf88-4601-4ba4-92af-cb90dc69dcac)
![image](https://github.com/MCRcortex/vulkanite/assets/62649962/ffdfc107-e563-4d89-aab6-e95084b09717)
![image](https://github.com/MCRcortex/vulkanite/assets/62649962/390ac9e4-6b1e-4117-bc29-aff301180bf6)
![image](https://github.com/MCRcortex/vulkanite/assets/62649962/08242702-53fc-4d1f-b23c-21a715bc8325)

**Comment by Bipbip2109** [comment]
I get that too, I think that this is just the shader lacking any kind of denoiser, and not an issue with the mod itself

**Comment by MCRcortex** [comment]
This is the fact that the shader is 3 days old and does not have a denoiser yet

**Comment by Coloryr** [comment]
![image](https://github.com/MCRcortex/vulkanite/assets/26276037/e4301679-eb26-4ab8-9324-5b03acf36de3)
![image](https://github.com/MCRcortex/vulkanite/assets/26276037/695691e3-6649-4511-a1a9-b367973e4fd4)
